baseurl = "https://r-u-s-s-e-l-l.github.io/" # Hostname (and path) to the root.
title = "Russell Ijaya" # Site title.
theme = "coder" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.
publishDir = "r-u-s-s-e-l-l.github.io"

[params] # theme parameters
    author = "Russell Ijaya" # Author's name.
    #info = "Full Stack DevOps and Magician" # Author's job title or info.
    description = "Russell Ijaya's personal website" # Site description.
    keywords = "blog,photography,personal" # Site keywords.
    #avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "Enter a text here." # Add footer content

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = ["css/homepage.css", "css/zoom.css", "css/navbar.css", "css/list.css", "css/single.css", "css/about.css"]

    # Custom JS
    custom_js = ["js/zoom.js", "js/transition.js"]

    # RTL support
    rtl = false

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

[taxonomies]
  level = "levels"
# Social links
#[[params.social]]
#    name = "Github"
#    weight = 1
#    url = "https://github.com/johndoe/"
#[[params.social]]
#    name = "Twitter"
#    weight = 2
#    url = "https://twitter.com/johndoe/"
#[[params.social]]
#    name = "LinkedIn"
#    weight = 3
#    url = "https://www.linkedin.com/in/johndoe/"

# Menu links
[[menu.main]]
    name = "Visuals"
    weight = 1
    url  = "/visuals"
[[menu.main]]
    name = "Things"
    weight = 2
    url = "/things"
[[menu.main]]
    name = "Words"
    weight = 3
    url  = "/words"
[[menu.main]]
    name = "About"
    weight = 4
    url = "/about"
